ALTER TABLE activity_logs
    MODIFY COLUMN action_type ENUM(
        'SCHEDULE_CREATED', 'SCHEDULE_UPDATED', 'SCHEDULE_DELETED',
        'VOTE_CREATED', 'VOTE_UPDATED', 'VOTE_DELETED', 'VOTE_CLOSED', 'VOTE_PARTICIPATED',
        'MEMBER_JOINED', 'MEMBER_LEFT', 'MEMBER_ROLE_CHANGED',
        'COMMENT_CREATED', 'COMMENT_DELETED', 'COMMENT_LIKED',
        'INVITATION_CREATED', 'INVITATION_REVOKED'
    ) NOT NULL;
