-- 일정 세부 수정(제목·메모·표시 순서)은 공유 피드에 노출하지 않고 내 활동에만 남긴다(정책 2절).
-- 공유 대상인 SCHEDULE_UPDATED와 구분하기 위해 별도 액션 타입을 추가한다.
ALTER TABLE activity_logs
    MODIFY COLUMN action_type ENUM(
        'SCHEDULE_CREATED', 'SCHEDULE_UPDATED', 'SCHEDULE_DETAIL_UPDATED', 'SCHEDULE_DELETED',
        'VOTE_CREATED', 'VOTE_UPDATED', 'VOTE_DELETED', 'VOTE_CLOSED', 'VOTE_PARTICIPATED',
        'MEMBER_JOINED', 'MEMBER_LEFT', 'MEMBER_ROLE_CHANGED',
        'COMMENT_CREATED', 'COMMENT_DELETED', 'COMMENT_LIKED',
        'INVITATION_CREATED', 'INVITATION_REVOKED'
    ) NOT NULL;
