-- 정책상 미기록 액션 타입 제거(정책 2절)
-- VOTE_PARTICIPATED: 정책 확정 전 코드가 남긴 익명성 위반 기록 → 삭제
DELETE FROM activity_logs
WHERE action_type IN ('VOTE_PARTICIPATED', 'INVITATION_CREATED', 'INVITATION_REVOKED');

ALTER TABLE activity_logs
    MODIFY COLUMN action_type ENUM(
        'SCHEDULE_CREATED', 'SCHEDULE_UPDATED', 'SCHEDULE_DETAIL_UPDATED', 'SCHEDULE_DELETED',
        'VOTE_CREATED', 'VOTE_UPDATED', 'VOTE_DELETED', 'VOTE_CLOSED',
        'MEMBER_JOINED', 'MEMBER_LEFT', 'MEMBER_ROLE_CHANGED',
        'COMMENT_CREATED', 'COMMENT_DELETED', 'COMMENT_LIKED'
    ) NOT NULL;
