package com.groom.moigo.domain.activity.entity;

public enum ActivityActionType {
    SCHEDULE_CREATED,
    SCHEDULE_UPDATED,
    SCHEDULE_DELETED,
    VOTE_CREATED,
    VOTE_UPDATED,
    VOTE_DELETED,
    VOTE_CLOSED,
    VOTE_PARTICIPATED,
    MEMBER_JOINED,
    MEMBER_LEFT,
    MEMBER_ROLE_CHANGED,
    COMMENT_CREATED,
    COMMENT_DELETED,
    INVITATION_CREATED,
    INVITATION_REVOKED
}
